# Generated by Django 3.0.6 on 2020-05-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_todotask_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='todotask',
            name='modified_info',
            field=models.TextField(null=True),
        ),
    ]
