# Generated by Django 3.0.6 on 2020-05-16 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='todolist',
            table='list',
        ),
    ]
