# Generated by Django 3.0.6 on 2020-05-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20200516_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovaEntidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sort', models.IntegerField()),
            ],
            options={
                'db_table': 'nova_entidade',
            },
        ),
    ]
